In [ ]:
# softmax function
# 计算exponential
# 按行求和
# 每行都要除以计算的和

In [1]:

import numpy as np

m = np.random.rand(10,10)*10+1000
print(m)


[[1004.74064902 1009.46384662 1006.74858414 1008.89334934 1009.36785251
  1001.2694593  1003.06334101 1008.06648503 1009.89876102 1002.33076093]
 [1000.23912792 1005.9473167  1001.81828285 1004.81328331 1006.14669254
  1005.40343997 1009.36476412 1004.10742804 1007.73709745 1003.22346611]
 [1002.74252474 1001.44503555 1003.16702264 1006.80499869 1008.48741368
  1002.17757144 1004.63361442 1002.78739591 1000.60292825 1006.31050816]
 [1007.71995073 1008.1018044  1008.485192   1005.68487635 1001.97076066
  1001.77310417 1001.31008186 1003.34220285 1006.855943   1001.17916754]
 [1009.85715126 1004.93835643 1001.34922334 1003.24084267 1004.77557669
  1003.94853651 1004.90022319 1006.26214713 1008.92352982 1000.71450095]
 [1003.56907626 1009.1759929  1008.4603976  1005.15872878 1003.04441425
  1000.33416207 1004.71464061 1004.33839439 1002.54551448 1002.7704715 ]
 [1003.00413697 1009.46960384 1006.34425754 1007.16290285 1005.61820412
  1004.49529354 1002.66720472 1005.49027771 1003.36159897 

In [4]:
# np.exp(m)
m_row_max = m.max(axis=1).reshape(10,1)
print(m_row_max, m_row_max.shape)

[[ 0.40815734]
 [-0.10483972]
 [-1.36973758]
 [-0.00222168]
 [-0.04160976]
 [-0.02701607]
 [ 0.10483972]
 [-0.78386407]
 [ 0.55123923]
 [ 0.05303234]] (10, 1)


In [5]:
m = m - m_row_max
print(m)

[[ -5.56626934  -0.30907484  -2.14698688   0.          -0.89745609
   -8.31469093  -6.81442016  -1.02741208  -0.28966078  -7.30642164]
 [ -9.55479338  -3.3126077   -6.5642911   -3.56706897  -3.605619
   -3.6677132    0.          -4.47347201  -1.9383273   -5.90071941]
 [ -5.7864987   -6.54999099  -3.95065346  -0.31045573   0.
   -5.62868387  -3.46625184  -4.52860628  -7.80759863  -1.54877949]
 [ -2.17658862  -1.26073804   0.          -2.79809397  -7.88416892
   -7.40066705  -8.15730031  -5.34131524  -2.92209979  -8.04763602]
 [  0.          -4.38479793  -7.09658058  -5.20273957  -5.03996481
   -5.18584663  -4.52777089  -2.38198288  -0.81512489  -8.47291453]
 [ -6.30266869  -0.16175515   0.          -3.29944714  -6.78572093
   -8.81481475  -4.72794716  -4.32032931  -7.20773391  -6.43153766]
 [ -6.99946378   0.          -2.24799586  -1.42712888  -4.34378686
   -4.78553908  -6.90723884  -3.30030178  -6.52350521  -3.67374153]
 [ -6.54566409  -4.9963497   -5.27552435  -0.83038021  -6.9285620

In [6]:
m_exp = np.exp(m)
print(m_exp)

[[3.82472261e-03 7.34125827e-01 1.16835668e-01 1.00000000e+00
  4.07605255e-01 2.44892570e-04 1.09782957e-03 3.57932062e-01
  7.48517433e-01 6.71214605e-04]
 [7.08607849e-05 3.64210746e-02 1.40982301e-03 2.82385004e-02
  2.71706211e-02 2.55347961e-02 1.00000000e+00 1.14076396e-02
  1.43944525e-01 2.73747476e-03]
 [3.06870785e-03 1.43012848e-03 1.92421237e-02 7.33112776e-01
  1.00000000e+00 3.59330146e-03 3.12338811e-02 1.07957118e-02
  4.06633354e-04 2.12507182e-01]
 [1.13427817e-01 2.83444756e-01 1.00000000e+00 6.09260788e-02
  3.76659516e-04 6.10845160e-04 2.86635179e-04 4.78956713e-03
  5.38205569e-02 3.19857166e-04]
 [1.00000000e+00 1.24654068e-02 8.27931132e-04 5.50147210e-03
  6.47397614e-03 5.59519756e-03 1.08047342e-02 9.23672429e-02
  4.42584050e-01 2.09054719e-04]
 [1.83141079e-03 8.50649461e-01 1.00000000e+00 3.69035641e-02
  1.12979291e-03 1.48516462e-04 8.84460898e-03 1.32955045e-02
  7.40834051e-04 1.60997333e-03]
 [9.12371070e-04 1.00000000e+00 1.05610671e-01 2.39996995e

In [7]:
m_exp_row_sum = m_exp.sum(axis = 1).reshape(10,1)
print(m_exp_row_sum, m_exp_row_sum.shape)

[[3.37085491]
 [1.27693532]
 [2.01539045]
 [1.51800277]
 [1.57682907]
 [1.91515367]
 [1.43257931]
 [2.0183745 ]
 [2.33735895]
 [1.98651828]] (10, 1)


In [8]:
m_softmax = m_exp / m_exp_row_sum
print(m_softmax)

[[1.13464469e-03 2.17786244e-01 3.46605450e-02 2.96660648e-01
  1.20920439e-01 7.26499884e-05 3.25682832e-04 1.06184357e-01
  2.22055667e-01 1.99122959e-04]
 [5.54928539e-05 2.85222549e-02 1.10406768e-03 2.21142763e-02
  2.12779933e-02 1.99969378e-02 7.83125024e-01 8.93360803e-03
  1.12726560e-01 2.14378499e-03]
 [1.52263689e-03 7.09603683e-04 9.54759102e-03 3.63757195e-01
  4.96181771e-01 1.78293068e-03 1.54976824e-02 5.35663541e-03
  2.01764057e-04 1.05442190e-01]
 [7.47217455e-02 1.86722159e-01 6.58760325e-01 4.01356835e-02
  2.48128345e-04 4.02400556e-04 1.88823883e-04 3.15517680e-03
  3.54548475e-02 2.10709211e-04]
 [6.34184150e-01 7.90536341e-03 5.25060801e-04 3.48894640e-03
  4.10569305e-03 3.54838560e-03 6.85219118e-03 5.85778414e-02
  2.80679789e-01 1.32579189e-04]
 [9.56273546e-04 4.44167732e-01 5.22151312e-01 1.92692444e-02
  5.89922848e-04 7.75480653e-05 4.61822418e-03 6.94226514e-03
  3.86827472e-04 8.40649688e-04]
 [6.36872992e-04 6.98041634e-01 7.37206455e-02 1.67527894e

In [9]:
print(m_softmax.sum(axis = 1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
