In [1]:
import numpy as np

# 使用普通一维数组生成numpy一维数组
data = [6,7.5,8,0,1]
arr = np.array(data)
print(arr)
print(arr.dtype) # 类型
print('')


[6.  7.5 8.  0.  1. ]
float64



In [2]:
# 使用普通二维数组生成numpy二维数组
data = [[1,2,3,4],[5,6,7,8]]
arr = np.array(data)
print(arr)
print(arr.shape) # 维度
print('')


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)



In [3]:
# 使用zeros/empty
print(np.zeros(10)) # 生成包含10个0的一维数组
print(np.zeros((3, 6))) # 生成3*6的二维数组
print(np.empty((2,3,2))) # 生成2*3*2的三维数组，所有元素未初始化
print('')


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[8.82769181e+025 7.36662981e+228]
  [7.54894003e+252 2.95479883e+137]
  [1.42800637e+248 2.64686750e+180]]

 [[1.09936856e+248 6.99481925e+228]
  [7.54894003e+252 7.67109635e+170]
  [2.64686750e+180 5.63234836e-322]]]



In [4]:
# 使用arange生成连续元素
print(np.arange(15)) # [0,1,2, ... ,14]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
